### ISSUE TITLE
confusion in Dataset directory structure

### ISSUE THREAD

**Issue by hars-singh** [bo-miao/MAMP#3]
Hi, Thanks for the great work!

I am facing some errors. I highly doubt the dataset directory structure. I am using the following structure.
![image](https://user-images.githubusercontent.com/53997601/130325147-9eab428c-94e5-4c8e-b97c-c44ef1760282.png)

Datapath in my train.sh looks like this.

![image](https://user-images.githubusercontent.com/53997601/130325216-da682fda-fa14-4e61-8a46-c8c4e2975fc9.png)

Am I doing something wrong here?

**Comment by bo-miao** [comment]
Hi,

You need to use `train_all_frames` which consists of the consecutive frames of training videos.
The structure of folder `all` should be 'all/video_names/consecutive_video_frames'

**Comment by hars-singh** [comment]
Thanks, it helped!!
