### ISSUE TITLE
Application for grayscale images

### ISSUE THREAD

**Issue by loopdigga96** [bo-miao/MAMP#5]
Hello! Thank you for publishing the paper and the code. I was wondering if your approach could be applied to grayscale images?

**Comment by bo-miao** [comment]
> Hello! Thank you for publishing the paper and the code. I was wondering if your approach could be applied to grayscale images?

Hi,

MAMP adopts two channels to extract features for matching and one dropped channel as the pseudo label for pseudo mask propagation.
 
Yes. You can design your image format to replace the "matching" channels or the "pseudo label" channel. Intuitively, the "pseudo label" channels should have low correlation with "matching" channel to avoid trivial solution, i.e., to prevent the model from predicting missing data rather than learning matches.

**Comment by loopdigga96** [comment]
Thanks @bo-miao, if you have such example of decorrelated channels in mind, it would be great to hear.

**Comment by bo-miao** [comment]
> Thanks @bo-miao, if you have such example of decorrelated channels in mind, it would be great to hear.

An example is Lab color space, it has fewer channel-wise correlations compared with RGB color space [1].

[1] Reinhard, E.; Adhikhmin, M.; Gooch, B.; and Shirley, P. 2001. Color transfer between images. IEEE Computer graphics and applications, 21(5): 34–41.

**Comment by loopdigga96** [comment]
@bo-miao  Okay, but is it valid to represent single channel grayscale image with LAB?

**Comment by bo-miao** [comment]
> @bo-miao Okay, but is it valid to represent single channel grayscale image with LAB?

The data need at least 2 channels (one for matching and one as label). You can try to combine multi-formats together, e.g., one format for matching and another as label. There would be many kinds of combinations.

**Comment by loopdigga96** [comment]
As far as I know there is only one way of representing grayscale images. Using single channel for pixel intensity. What other multi-formats are you referring?

**Comment by bo-miao** [comment]
> As far as I know there is only one way of representing grayscale images. Using single channel for pixel intensity. What other multi-formats are you referring?

The formats that I said are different colour spaces, Lab, RGB, etc. Compared to changing colour spaces, I would recommend optimizing the framework since that belongs to strong novelty.
